name: Essential Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-mock pytest-asyncio
        pip install -e .
    
    - name: Run critical tests only
      env:
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        GEMINI_MODEL: gemini-2.0-flash-lite  # Cheapest model
      run: |
        # Test core functionality with real API (cheapest model)
        pytest tests/test_package.py tests/test_min_python_requirements.py tests/test_server.py -v
    
    - name: Test package building
      run: |
        python -m build
        
    - name: Test entry points
      run: |
        python -c "import pkg_resources; eps = [ep for ep in pkg_resources.iter_entry_points('console_scripts') if 'task-list' in ep.name]; print(f'Found {len(eps)} entry points')"