name: Retry Tests on Runner Failure

on:
  workflow_run:
    workflows: ["Tests"]
    types:
      - completed

jobs:
  retry-on-runner-failure:
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    runs-on: ubuntu-latest
    steps:
      - name: Check if runner failure
        id: check
        uses: actions/github-script@v7
        with:
          script: |
            const run = context.payload.workflow_run;
            const jobs = await github.rest.actions.listJobsForWorkflowRun({
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: run.id
            });
            
            const runnerFailure = jobs.data.jobs.some(job => 
              job.conclusion === 'failure' && 
              job.steps.some(step => 
                step.conclusion === 'failure' && 
                step.name === 'Set up job' || 
                (step.output && step.output.includes('Runner'))
              )
            );
            
            core.setOutput('should_retry', runnerFailure);
            return runnerFailure;

      - name: Trigger retry
        if: steps.check.outputs.should_retry == 'true'
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.actions.reRunWorkflow({
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: context.payload.workflow_run.id
            });
            console.log('Workflow retry triggered due to runner failure');