name: Retry Tests on Runner Failure

on:
  workflow_run:
    workflows: ["Tests"]
    types:
      - completed

jobs:
  retry-on-runner-failure:
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    runs-on: ubuntu-latest
    steps:
      - name: Check and retry if runner failure
        uses: actions/github-script@v7
        with:
          script: |
            const run = context.payload.workflow_run;
            
            // Get jobs for the failed workflow
            const jobs = await github.rest.actions.listJobsForWorkflowRun({
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: run.id
            });
            
            // Check if any job failed due to runner issues
            const runnerFailure = jobs.data.jobs.some(job => 
              job.conclusion === 'failure' && 
              job.steps && job.steps.some(step => 
                step.conclusion === 'failure' && 
                (step.name === 'Set up job' || 
                 (step.name && step.name.includes('Runner')))
              )
            );
            
            if (runnerFailure) {
              console.log('Detected runner failure, triggering retry...');
              await github.rest.actions.reRunWorkflow({
                owner: context.repo.owner,
                repo: context.repo.repo,
                run_id: run.id
              });
              console.log('Workflow retry triggered');
            } else {
              console.log('Failure was not due to runner issues, not retrying');
            }