name: Version Bump Check

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - 'src/**'
      - 'pyproject.toml'

jobs:
  check-version:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Check version bump
      run: |
        # Get version from main branch
        git fetch origin master
        MAIN_VERSION=$(git show origin/master:pyproject.toml | python -c "import sys, tomllib; print(tomllib.loads(sys.stdin.read())['project']['version'])")
        
        # Get version from PR branch
        PR_VERSION=$(python -c "import tomllib; print(tomllib.load(open('pyproject.toml', 'rb'))['project']['version'])")
        
        echo "Main branch version: $MAIN_VERSION"
        echo "PR branch version: $PR_VERSION"
        
        if [ "$MAIN_VERSION" = "$PR_VERSION" ]; then
          echo "::warning::Version has not been bumped. Current version is $MAIN_VERSION"
          echo "Please update the version in pyproject.toml before merging."
          exit 1
        else
          echo "✅ Version bumped from $MAIN_VERSION to $PR_VERSION"
        fi